config/routes.rb
Bdb::Application.routes.draw do

  # resources :species, :only => [:show], :defaults => { :format => 'json' }
  get 'species/:id', to: 'species#show', defaults: { format: 'json' }
  get "species", to: 'species#search', defaults: {format: 'json'}

  
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users,  :skip => [:registrations]  #:controllers => { :invitations => "invitations" },
  
  resources :specimens, :only => [:index, :show, :edit]
  # printing a specimen has a side effect of updating printed date, so it's a put not a get
  
  
   
  resources :teams do 
    # dashboard page
    get 'collect' => 'dashboard#collect'
             
    
    resources :managers
    
    resources :collection_events do
      resource :specimens, :only => [:new, :create]
    end
    # , :except => [:new, :create]
    resources :specimens, :only => [:index, :show, :edit, :update, :destroy] do 
      collection do
        put "print", to: 'specimens#print_labels',  defaults: { format: 'pdf'}
      end
    end
    
    
    resources :sites do 
      resources :collection_events do
        resources :specimens
      end
    end
    
  end
  
  as :user do
    get 'users/registration' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    put 'users/registration' => 'devise/registrations#update', :as => 'user_registration' 
    delete 'users/registration' =>  'devise/registrations#delete', :as => 'delete_user_registration'          
  end 
  
  resources :users do 
    member do
       put 'invite'
     end
  end
   
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  load_and_authorize_resource :team  
  # load_and_authorize_resource :sites, :through => :team
  # load_and_authorize_resource :collection_events, :through => :team
  
  def collect
    @sites = @team.sites
    @collection_events = @team.collection_events
    @specimens = @team.specimens
  end
end

app/views/dashboard/collect.html.erb
<%= content_for :head do %>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() { $("#site_select").select2({ width: 'resolve' }); });
    $(document).ready(function() { $("#event_select").select2({ width: 'resolve' }); });
</script>
<style type="text/css" media="screen">
.wide-label {
    width:8em;
    
}  
</style>
<% end %>

<% title("Bee Collection Activity") %>

<% content_for :subnav do -%>
    <ul class="nav">
        <li><%= iconified_link_to 'icon-map-marker', "#{@sites.count} sites", team_sites_path(@team) %></li>
        <li><%= iconified_link_to 'icon-calendar', "#{@collection_events.count} events", team_collection_events_path(@team) %></li>
        <li><%= iconified_link_to 'icon-heart', "#{@specimens.count} specimens", team_specimens_path(@team) %></li>
        <li><%= iconified_link_to 'icon-qrcode', "Print new labels (#{@specimens.unprinted.count})", print_team_specimens_path(@team), :method=>:put, :confirm => "Make PDF and update print date all unprinted labels?" %>
    </ul>
<% end -%>

<!-- <div class="row">         -->
    <div class="well">
        <h4>Add collection event</h4>
        <%= render "collection_events/dashboard_new", {:collection_event => (CollectionEvent.new || @collection_event)}%>            
    </div>      
            
    <div class="well">
        <p>
            <b>New Specimens: </b> Select Event@Site <%= select_tag "Site", options_from_collection_for_select(@collection_events, 'id', "to_s"), :id=>'event_select' %>
            <input type = "button", value="New Specimen form", onclick = "{goto_new_specimens()}", class ='btn' >
        </p>
    </div>
<!-- </div> -->
<div class="row">
    <div class="span4">
         <%= render "layouts/gmap", {:sites => @sites, :height=>'400', :width=>'100%'} %>
    </div>
    <div class="span8">
        <p class="lead">Collection Events   </p>
         <%= render "collection_events/collection_events", { :collection_events => @collection_events } %>
         <%# show above list instead of calendar %>                
         <%#= render "collection_events/calendar",    { :collection_events => @collection_events } %>
    </div>
</div>

<% content_for :head do -%>
<script type="text/javascript" charset="utf-8">
    function goto_new_event(){
        goto_rails_path('<%= new_team_site_collection_event_path(@team,-1) %>', 'site_select');
    }   
    
    function goto_new_specimens(){
        goto_rails_path('<%= new_team_collection_event_specimens_path(@team,-1) %>', 'event_select');
    }
    function goto_rails_path(path_template, selector_id){
        var resource_selector = document.getElementById(selector_id);
        var resource_id = resource_selector.options[resource_selector.selectedIndex].value;
        if (resource_id != ""){
           window.location =  path_template.replace("/\-1","/"+resource_id);
        }
    }
    
</script>
<% end -%>