config/routes.rb
Bdb::Application.routes.draw do

  # resources :species, :only => [:show], :defaults => { :format => 'json' }
  get 'species/:id', to: 'species#show', defaults: { format: 'json' }
  get "species", to: 'species#search', defaults: {format: 'json'}

  
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users,  :skip => [:registrations]  #:controllers => { :invitations => "invitations" },
  
  resources :specimens, :only => [:index, :show, :edit]
  # printing a specimen has a side effect of updating printed date, so it's a put not a get
  
  
   
  resources :teams do 
    # dashboard page
    get 'collect' => 'dashboard#collect'
             
    
    resources :managers
    
    resources :collection_events do
      resource :specimens, :only => [:new, :create]
    end
    # , :except => [:new, :create]
    resources :specimens, :only => [:index, :show, :edit, :update, :destroy] do 
      collection do
        put "print", to: 'specimens#print_labels',  defaults: { format: 'pdf'}
      end
    end
    
    
    resources :sites do 
      resources :collection_events do
        resources :specimens
      end
    end
    
  end
  
  as :user do
    get 'users/registration' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    put 'users/registration' => 'devise/registrations#update', :as => 'user_registration' 
    delete 'users/registration' =>  'devise/registrations#delete', :as => 'delete_user_registration'          
  end 
  
  resources :users do 
    member do
       put 'invite'
     end
  end
   
  
end

app/models/specimen.rb
# require 'lib/model_to_csv.rb'
class Specimen < ActiveRecord::Base
  
  include ModelToCSV
  
  attr_accessible :sex,:collection_event_id, :collectors, :determination_status, :determiner, :hostplant_id, :hostplant_literal, :idcode, :label_printed_on, :location, :notes, :status,:species_id,:taxa
  belongs_to :collection_event
  belongs_to :species
  belongs_to :hostplant

  attr_accessor :bulk_insert_count
  attr_accessible :bulk_insert_count
  
  scope :unprinted, -> {where('label_printed_on IS NULL')}
  scope :undetermined, -> {where('species_id IS NULL')}
  scope :determined, -> {where('species_id IS NOT NULL')}
  
  delegate :site, :to => :collection_event, :allow_nil => true
  
  validates :collectors, :presence => true
  validates_associated :collection_event
  
  # create a bag of n identical new specimens
  def self.bulk_new(n = 1, specimen_params)
    new_specimens = []
  
    if (n.is_a? Integer) && n > 0
      (1..n).each do 
        begin       
          new_specimens << Specimen.new(specimen_params)
        rescue
          exit
        end
      end
    end  
    
    new_specimens  
  end


  # bulk save a bunch of specimens, wrapped in a transaction 
  def self.bulk_save(specimens)
    ActiveRecord::Base.transaction do
      begin
        specimens.each do |specimen|
          specimen.save
        end    
      rescue
        exit
      end
    end
  end
  
  
  def collection_site
    self.collection_event.site
  end
  
  # special display of specimen IDs to make them unique for this project
  
  def team
    collection_event.site.team
  end
  
  def coded_id
    project_prefix + sprintf("%04d", self.id) if self.id?
  end
  
   
  def shortened_geoname
     s = LocShortener.shorten("#{site.country}: #{site.stateprov}#{(', ' + site.county if site.county?)}" )
     s.truncate(30,:omission=>".")
  end
  
  def shortened_locality(n=30)
    locality = self.collection_event.site.locality
    LocShortener.shorten(locality).truncate(n, :seperator=>' ', :omission =>".")
  end
  
  def shortened_collectors
    collectors.blank? ? "" : collectors.truncate(20, :separator=>",", :omission=>",et al")
  end
  
  def shortened_location(n = 5)
    location.blank? ? "" :location.truncate(n, :omission=>".")
  end
  
  def host_plant_str
    if hostplant
      hostplant.scientific_name
    else
      hostplant_literal
    end
  end
  
  def site_str
    site = collection_event.site
    site.to_s if site
  end
  
  def scientific_name_str
    species.blank? ? 'undetermined' : species.scientific_name
  end
  
  def set_print_date(printdate = Time.now)
     update_attribute("label_printed_on",printdate.strftime("%d/%m/%Y"))
  end

  def site_name_str
    site = self.site
    site.name if site
  end
  
  def export_data 
    collection_event ||= self.collection_event
    site ||= self.specimen.site
      {
      "Specimen ID Code"      => self.coded_id,
      "Collection Site"       => self.site_name_str,
      "State/Prov"            => self.site.stateprov,
      "Country"               => self.site.country,
      "Treatment"             => self.site.treatment.to_s,
      "Collection on"         => self.collection_event.date_start,
      "Collection end date"   => self.collection_event.date_end,
      "Collection time"       => self.collection_event.collection_time,
      "Collected by"          => self.specimen.collectors,
      "Host plant"            => self.hostplant_str,
      "Species"               => self.scientific_name_str,
      "Sex"                   => self.sex,
      "Specimen Status"       => self.status,
      "Location"              => self.location,
      "Determination status"  => self.determination_status,
      "Determiner"            => self.determiner,
      "Notes"                 => self.notes
     }
   end
   
   def csv_headers(x)
     export_data.keys
   end
  
   def csv_dump(header_val)
     export_data.values
   end
  

  # CLASS METHODS
  
  def self.to_hash
    # # all.to_a.map(&:serializable_hash)
  end
  
 
  
  def self.export_template
    {
    "Specimen ID Code"      =>'coded_id',
    "Collection on"         =>'collection_event',
    "Collected by"          =>'collectors',
    "Host plant"            =>'host_plant_str',  
    "Species"               =>'scientific_name_str',
    "Sex"                   =>'sex',
    "Status"                =>'status',
    "Location"              =>'location',
    "Determination status"  =>'determination_status',
    "Determiner"            =>'determiner',
    "Notes"                 =>'notes',
     "Collection Site"      =>'site.name',
     "State/Prov"           =>'site.stateprov',
     "Treatment"            =>'site.treatment.to_s'
   }
  end
  
  def self.export_header
    Specimen.export_template.keys
  end
  
  # def self.unprinted(team=nil)
  #   if team.blank?
  #       self.where("label_printed_on IS NULL")
  #     else
  #       team.specimens.where("label_printed_on IS NULL")
  #     end
  #     
  # end
  
  def export_data
    Specimen.export_template.values.map { |meth| self.send(meth).to_s}
  end
  
  
  def csv_headers
    export_data.keys
  end
  
  def csv_dump
    export_data.values
  end
  
  
  def to_hash(options={})
    {
    "Specimen ID Code"      => self.coded_id,
    "Collection on"         => self.collection_event.to_s,
    "Collected by"          => "#{self.collectors}, #{self.team.to_s}",
    "Host plant"            =>  self.hostplant.to_s,  
    "Species"               => species_id? ? "<i>#{self.species.to_s}</i>" : "undetermined",
    "Sex"                   => self.sex,
    "Label printed on"      => self.label_printed_on ,
    "Status"                => self.status ,
  "Site Collection Location"  => self.location ,
    "Determination status"  => self.determination_status ,
    "Determiner"            => self.determiner ,
    "Notes"                 => self.notes }
    
     # self.hostplant_id + " " + 
  end
  
  def to_s 
     "#{coded_id} collected #{self.collection_event.to_s}"
  end
  
  # to do:
  # create a project table and use prefix from that for this value
  # store this value along with ID in a non-mutable table column for safe keeping and auditing
  def project_prefix
      "ICP" +  two_digit_year
  end
  
  def insert_year_digits
    self.date_created.strftime("%y")
  end
  
  def two_digit_year
    # to fix labels printed with current year because of poor programming, 
    # the project prefix year is based on date the record is created, not date specimen was collected
    # future project prefixes should not include a year
    if created_at.blank? 
      "  "
    else
      created_at.strftime("%y")
    end    
  end
  
end

app/controllers/specimens_controller.rb
class SpecimensController < ApplicationController
  include SpecimensHelper
  
  load_and_authorize_resource :team
  # load_and_authorize_resource :specimen, through: :team

  def index
    @team = current_team
    @specimens = []
    # @specimens = @team.specimens.all
    if params[:collection_event_id] && @collection_event = CollectionEvent.find(params[:collection_event_id])
       @specimens = @collection_event.specimens.all
    elsif params[:ids]
      unless (id_list=params[:ids].split(',')).blank?
         @specimens = Specimen.find(id_list) 
      end
     
    elsif params[:site_id] && @site = Site.fin(params[:site_id])
       @specimens = @site.specimens.all
    else
       @specimens = @team.specimens.all
    end 
    
    #  search/sort ?
    respond_to do |format|
      format.html  
      format.xls
      format.xlsx  
      format.json { render json: @specimens }
      format.csv  { render :text => SpecimenExporter.to_csv(@specimens) unless @specimens.empty? }
      format.pdf  do
        send_pdf_labels(@specimens, params[:label_type] )
      end
    end
  end

  # PUT team/specimens/print
  def print_labels
    @team = current_team
    if params[:id]
      @specimens = [Specimen.find(params[:id].split(","))]
    else
      @specimens = @team.specimens.unprinted
    end

    if @specimens.empty?
      redirect_to :back, alert:  "No specimens with un-printed labels (No PDF generated)"
    else  
      @specimens.each {|s| s.set_print_date()}
      respond_to do |format|
        format.html  
        format.pdf  do
            send_pdf_labels(@specimens, params[:label_type])
        end
      end
    end
  
  end
  
    
  def show
    @specimen = Specimen.find(params[:id])
    @site = @specimen.collection_event.site
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @specimen }
      format.pdf do
          send_pdf_labels([@specimen], params[:label_type])
      end
    end
  end
  

  
  # GET /specimens/new
  # GET /specimens/new.json
  def new
    if params[:collection_event_id]
      @collection_event = CollectionEvent.find(params[:collection_event_id])
      @site = @collection_event.site
      @specimen = @collection_event.specimens.build
    else
      @specimen = Specimen.new
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @specimen }
    end
  end

  # def duplicate
  #   if params[:specimen_id] && source_specimen = Specimen.find(params[:specimen_id])
  #     @specimen = Specimen.new(source_specimen.to_param)
  #   end
  # end
  
  # GET /specimens/1/edit
  def edit
    @specimen = Specimen.find(params[:id])
    @collection_event = @specimen.collection_event
  end

  # POST /specimens
  # POST /specimens.json
  def create
    @team = current_team
    @site = Site.find(params[:site_id])
    @collection_event = CollectionEvent.find(params[:collection_event_id])
    bulk_insert_count = params[:specimen][:bulk_insert_count].to_i
    bulk_insert_count = 1 unless (bulk_insert_count.is_a? Integer and bulk_insert_count > 0)
    
    @specimens = Specimen.bulk_new(bulk_insert_count, fix_collector_array(params[:specimen]))  # do bulk by default, even if just 1
    
    respond_to do |format|
      if Specimen.bulk_save(@specimens)
        format.html { redirect_to team_collection_event_path(@team,params[:collection_event_id]), notice:  "#{@specimens.count} specimen(s)  successfully created. " }
        format.json { render json: @specimen, status: :created, location: @specimen }
      else
        format.html { render action: "new" }
        format.json { render json: @specimen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /specimens/1
  # PUT /specimens/1.json
  def update
    @specimen = Specimen.find(params[:id])
    
    respond_to do |format|

      specimen_params = fix_collector_array(params[:specimen])
      if @specimen.update_attributes(specimen_params)
        format.html { redirect_to team_specimens_path(current_team), notice: "Specimen #{@specimen.coded_id} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @specimen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specimens/1
  # DELETE /specimens/1.json
  def destroy
    @specimen = Specimen.find(params[:id])
    @specimen.destroy

    respond_to do |format|
      format.html { redirect_to specimens_url }
      format.json { head :no_content }
    end
  end


  
  private
  
  # my current use of select2 and simple form creates an array with empty strings.  need to squash them for comma list
  # should probl do this in the model  
  def fix_collector_array(specimen_params)
    
    if specimen_params[:collectors].class == [].class
      # in place changes
      specimen_params[:collectors].delete("")
      specimen_params[:collectors].compact!
    
      # convert to string
      specimen_params[:collectors] = specimen_params[:collectors].join(",")
    end
    
    specimen_params
  end
  
end

app/helpers/specimens_helper.rb
require 'csv'
require "open-uri"
require "specimen_exporter"
require "specimen_label"

module SpecimensHelper
  
  def specimen_nested_path(specimen = @specimen)
    team_site_collection_event_specimen_path(@team, specimen.collection_event.site, specimen.collection_event, specimen)
  end
 
  # def specimens_to_xls(specimens)
  #   SpecimenExporter.to_html(specimens)
  # end

  # superceded by lib/specimen_exporter.rb, remove in future commit
  # def specimen_export(specimens)
  #   if specimens.blank?
  #     return ("No specimens selected")
  #   end
  #
  #   csv_options = { :col_sep => ",",
  #                   :headers => Specimen.export_header,
  #                   :write_headers => true }
  #
  #   CSV.generate(csv_options) do |csv|
  #      specimens.each do |specimen|
  #        csv << specimen.export_data
  #      end
  #    end
  # end

  def send_pdf_labels(specimens, label_type)
      # label type from params here
      send_data SpecimenLabel.generate_pdf(specimens, label_type),  # TO DO : CHECK LABEL_TYPE PARAM
          filename: label_file_name(),
          stream: false,
          type: "application/pdf",
          disposition: "inline" 
  end
  
  def temp_pdf_file  
    "/tmp/" + label_file_name
  end
    
  def label_file_name
    timestamp = Time.now.utc.iso8601.gsub('-', '').gsub(':', '')
    "specimens_printed_#{timestamp}.pdf"
  end
    
  
end

app/views/specimens/_form.html.erb
<%= content_for :scripts do %>

    <script type="text/javascript" charset="utf-8">

        
       var entries_per_page = 20;
      
       $('#species_select').select2({
        width: 'resolve',
        placeholder: "species <%= specimen.species %>",
        dropdownCssClass: "bigdrop",
        ajax: {
          url: "<%= url_for(:controller=>'species', :action=>'search', :format=>:json) %>",
          dataType: 'json',
          quietMillis: 200,
          data: function (term, page) {
            return {
              q: term,
              page: page,
              per_page : entries_per_page
            };
          },
          results: function (data, page) {
            var more = (page * entries_per_page) < data.total
            return { results: data, more:more };
          }
        }

      });
   
       $('#species_select').change(function () {
           $("#determiner_input").val("<%= current_user.name %>");
       });
       
    </script>
<% end -%>

<!-- form for EDITING details of a single specimen -->
<%= simple_form_for( [@team, specimen], :html => {:class => 'form-horizontal' }) do |f| %>
  
<div class="row">

  <%= f.error_notification %>
    <div class="span6">
        <%= render :partial => "specimens/form_core", :locals => { :f => f, :collection_event => collection_event, :specimen=>specimen } %>
    </div>
        
   <div class="span6">
        <div class="form-inputs">
        
            <% if specimen.species_id? %>
                Current species is<em> <%=specimen.species.to_s %> </em>
                <% species_hint = "Selecting something will change the species" if specimen.species_id? %>
            <% end -%>
            
            <% species_label = "Select #{'different' if specimen.species_id? } species" %>
            <%= f.input :species_id, :label => species_label,  :hint => species_hint, :input_html=> { :id =>'species_select'} %>
            <%= f.input :sex %>

        <%= f.input :determination_status,:input_html=> { :id =>'determination_status'}  %>
        <%= f.input :determiner,:input_html=> { :id =>'determiner_input'} %> 
        </div>
    </div>
                  
  <div class="span10">
      <div class="well form-actions">
        <%= f.button :submit %>
        <%= cancel_button %>
      </div>
  </div>
</div>
  
<% end %>

app/views/specimens/_form_core.html.erb
<% collector_list = @team.users.all.collect {|u| u.collector_name} %>
<% collector_hash = Hash[@team.users.all.map{|u| [u.collector_name, u.collector_name]}] %>
<%= content_for :scripts do %>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() { 
        $("#site_loc_select").select2({ width: 'resolve' }); 
        $("#hostplant_select").select2({ width: 'resolve' });
        $("#collector_select").select2({ width: 'resolve' });
    });
</script>
<% end %>


<div class="form-inputs">
   
  <%= f.input :collectors, :collection => collector_hash, 
      :selected => (specimen.collectors.split(",") if specimen.collectors), 
      :hint =>"select one or more names from your team list", 
      :input_html=> { :id => 'collector_select',:multiple=>true} %>
     
  <%= f.association :hostplant,
      :input_html => { id:'hostplant_select'} 
      %>
  <%= f.input :hostplant_literal, :label=>"other host plant", :hint=>"If not listed, enter as <<common name (Genus species)>>" %>    
  <%= f.input :status, :label=>"Status of specimen", :hint=>"pinned, shipped, etc" %> 
  <%= f.input :location, :as =>:select, 
      :collection =>collection_event.site.loc_array, 
      :label =>"in-site location",
      :hint => "point of collection", 
      :input_html => { id:'site_loc_select'} %>
  <%= f.input :notes, 
      input_html: { cols:'60', rows: '5' }  
      %>
      
</div>

app/views/specimens/_form_new.html.erb
<%= simple_form_for( [@team,site,collection_event,specimen], :html => {:class => 'form-horizontal' }) do |f| %>

  <%= f.error_notification %>
  <%= render :partial => "specimens/form_core", :locals => { :f => f,:collection_event => collection_event, :specimen => specimen } %>

 <%= f.input  :bulk_insert_count, :label => "How Many to insert?", :hint =>"enter a number of specimens to add for this event", input_html: {value: '1'} %>

  <%= f.input :collection_event_id,  :as =>:hidden, :value => collection_event.id %>

  <div class="span10">
      <div class="well form-actions">
        <%= f.button :submit, :class=>'btn' %>
      </div>
  </div>
<% end %>

app/views/specimens/_label.html.erb
<%= site.locality %><br>
<% if site.county %><%= site.county %>, <% end -%> <%= site.stateprov %>}, <%= site.country %> <br>
<%= site.coordinates(precision=4) %>  <% if site.elevation %>, <%= site.elevation%>m <% end -%> <br>
<%= specimen.collectors %>

app/views/specimens/_specimen_table.html.erb
<%  if specimens.blank? %>
<div class="row">
    <div  class="alert alert-notice">
        No Specimens entered yet. 
    </div>
</div>
<% else %>
  
    <% content_for :head do %>
        <style type="text/css" media="screen">
        .row_selected {
            border: 1px solid #red;
        }
        </style>

        <script type="text/javascript" charset="utf-8">
            var oTable; // datatables table object
            
            var displayCountSelected = function() {
              var n =  fnGetSelected(oTable).length;
              var countText = n + " specimen" + (n === 1 ? "" : "s") + " selected";
              $( "#countDisplay" ).text( n.toString() );
            };
            
            var fnGetSelected = function( oTableLocal, selector  )
            {
                selector = typeof selector !== 'undefined' ? selector : ".DTTT_selected";
                // var rows;
                return (oTableLocal.$(selector));
            }
            
            var fnGetIds = function(rows){
                var ids = $(rows).map(function(i,v) { return($(v).attr('id'))});
                return(ids);
            }
         
            var fnBaseURL = function() {
                // set serverside
                return ("<%= team_specimens_path(@team) %>");
            }
            
            
            // generate a URL for the selected IDs
            var fnSelectedUrl = function(rows, format) {
                 format = typeof format !== 'undefined' ? format : "html";
                 var ids = fnGetIds(rows);
                 var print_url = fnBaseURL() + "." + format + "?ids=" + $(ids).toArray().toString();
                 return(print_url);            
             }
             
             var fnButtonAction = function(format){
                 var selectedRows = fnGetSelected( oTable );
                 if (selectedRows.length == 0) {
                     alert("Please select one or more rows");
                 } else {
                     var print_url = fnSelectedUrl(selectedRows,format);
                     location.href = print_url;
                 }
             }
            
            $(document).ready(function(){
                oTable = $('#specimens').dataTable({
                    "sDom": '<"row"<"span3"i><"span4"f><"span5"T>r> t<"row"<"span3"l>p>>', 
                    "iDisplayLength": 25,
                    "oTableTools": {"sSwfPath": "/swf/copy_csv_xls_pdf.swf",
                                    "sRowSelect": "multi",
                                    "fnRowSelected": function ( nodes ) {displayCountSelected();},
                                    "fnRowDeselected": function ( nodes ) {displayCountSelected();},
                                    "aButtons": 
                                        ["copy","select_all", "select_none",
                                          {"sExtends": "text",
                                           "sButtonText": "Labels",
                                           "fnClick": function ( nButton, oConfig, oFlash ) { fnButtonAction('pdf');}
                                          },
                                          {"sExtends": "text",
                                           "sButtonText": "CSV",
                                           "fnClick": function ( nButton, oConfig, oFlash ) { fnButtonAction('csv');}
                                          }
                                        ]
                    }
                });
                
                $("#specimens_info").append( '&nbsp;<span class="badge badge-info" id="countDisplay"></span>' );
                                      
            });
        </script>
    <% end -%>

    
    <table id="specimens">
    <thead>
      <tr>
        <th>Id Code</th>
        <th>Collection Site</th>
        <th>Date</th>
        <th>Host Plant</th>
        <th>Treatment</th>
        <th>Collectors</th>
        <th>Status</th>
        <th>Species</th>
        <th>Sex</th>
      </tr>
    </thead>
    <tbody>
    <% for specimen in specimens %>
      <% unless specimen.blank? || specimen.id.blank? %>
      <tr id="<%= specimen.id %>">
        <td> 
            <%= link_to specimen.coded_id, specimen_nested_path(specimen),:class=>'label specimen_id' %>
        </td>
        <td>
            <%= specimen.site.name %><br>
        </td>
        <td>
            <%= specimen.collection_event.date_start %><br/> 
        </td>
        <td>
            <em><%= specimen.hostplant.scientific_name if specimen.hostplant %></em>
        </td>
        <td>
            <%= specimen.location %>
        </td>
        <td>
            <%= specimen.collectors %>
        </td>
        <td>
            <%= specimen.status %> 
        </td>
        <td>
            <i><%= specimen.scientific_name_str %></i>
            <%= edit_button( edit_team_specimen_path(@team.id,  specimen.id), {:class=>" btn-mini "}, button_text='') if specimen.species.blank?  %>
        </td> 
        <td>
            <%= specimen.sex %>
        </td>
            
        <!-- 
         other fields not displayed    
             <td><%#= specimen.determination_status %></td>
             <td><%#= specimen.determiner %></td> 
        -->
      </tr>
     
      <% end -%>
    <% end -%>
    </tbody>
    </table>

   
    
<% end %>

app/views/specimens/edit.html.erb
<% title("Edit Specimen Details #{@specimen.coded_id if @specimen.id?}") %>
<!-- <h3><%= yield :title %></h3> -->

<% content_for :subnav do -%>
<ul class="nav pull-right">
    <li class="pull-right">
        <%= cancel_link_to :back, "Cancel Edits" %>
    </li>
</ul>
<% end %>

<%= render 'form', {:specimen => @specimen, :collection_event => @specimen.collection_event} %>

app/views/specimens/index.csv.erb
<!-- <%#  hash = {
  "Specimen ID Code"      =>'coded_id',
  "Collection on"         =>'collection_event',
  "Collected by"          =>'collectors',
  "Host plant"            =>'host_plant_str',  
  "Species"               =>'scientific_name_str',
  "Sex"                   =>'sex',
  "Status"                =>'status',
  "Location"              =>'location',
  "Determination status"  =>'determination_status',
  "Determiner"            =>'determiner',
  "Notes"                 =>'notes',
   "Collection Site"      =>'site.name',
   "State/Prov"           =>'site.stateprov',
   "Treatment"            =>'site.treatment.to_s'
 }
 %> -->

app/views/specimens/index.html.erb
<% title('Specimens') %>

<%= render :partial => "specimen_table", :locals => { :specimens => @specimens } %>

app/views/specimens/index.xls.erb
<% @headers = SpecimenExporter.data_headers(@specimens) %>
<h1>Specimen Data from ICP Bee Database</h1>

<table>
  <tr>
  <% for header in @headers %>
    <th><%= header %></th>
  <% end %>
  </tr>

  <% for specimen in @specimens %>
    <tr>
    <% @values = SpecimenExporter.new(specimen).export_data.values %>
    <% for value in @values %>
      <td><%= value %></td>
    <% end %>  
    </tr>
  <% end %>
</table>

<br />

app/views/specimens/index.xlsx.erb
<%# this is a crude Excel XML format, treating all values as string instead of proper data types %>
<%# uses values created by the SpecimenExporter class, not simply specimens table  %>

<% @headers = SpecimenExporter.data_headers(@specimens) %>

<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <% for header in @headers %>
          <Cell><Data ss:Type="String"><%= header %></Data></Cell>
        <% end %>      
      </Row>
      <% for specimen in @specimens %>
      <Row>
        <% for value in SpecimenExporter.new(specimen).export_data.values %>
           <Cell><Data ss:Type="String"><%= value %></Data></Cell>
        <% end %>
      </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>
    

app/views/specimens/new.html.erb
<% title("Add specimen(s) for  #{@collection_event.to_s}") %>

<% content_for :subnav do -%>
    <ul class="nav pull-right">
        <p><%= cancel_button %></p>        
    </ul>
<% end -%>
    <h4><em><%= @collection_event.specimens.count == 0  ? "No" : @collection_event.specimens.count %> specimens already entered</em></h4>

        <%= render 'form_new', {:specimen => @specimen, :collection_event => @collection_event, :site => @site } %>

app/views/specimens/show.html.erb
<% title("Specimen #{@specimen.coded_id}") %>

<% content_for :subnav do -%>
    <ul class="nav">
        <li>
            <%= iconified_link_to 'icon-calendar', 
                    "Collection Event", 
                    team_site_collection_event_path(@team.id, @specimen.collection_event.site.id, @specimen.collection_event.id) %>            
            
        </li>
        <li>
            <% site = @specimen.site -%>
            <%= iconified_link_to 'icon-map-marker',"Site Page", team_site_path(@team.id, site.id) -%>
        </li>
        <% if can? :update, @specimen %>
            <li>
                <%= iconified_link_to 'icon-pencil', "Edit", edit_team_specimen_path(@team.id,  @specimen.id) %>
            </li>    
            <li>
                <%= iconified_link_to 'icon-qrcode', "#{'Re-' if @specimen.label_printed_on }Print Label", print_team_specimens_path(@team, :id=>@specimen.id), {:method=>:put}  %>            
            </li>
            <li>
                <%= delete_button @specimen, {:class=>''} %>
            </li>
        <% end %>
        
    </ul>
<% end -%>
<div class="row">
    <div class="span6">

        
        <div class="well">
            <%= hash_table @specimen.to_hash %>
            <p>
                <%= link_to(team_specimen_path( @team, @specimen, :format=>:pdf), :class=>'btn btn-large' ) do %>
                    <embed src="<%= team_specimen_path( @team, @specimen, :format=>:pdf)  %>"  
                        width="200" height="100"style="overflow:hidden; width: 200px; height: 100px" >
                <% end -%>
            </p>
        </div>
        
    </div>
    
    <div class="span6">
        <p>
            <%= render "layouts/gmap", {:sites => [@site], :height=>'250', :width=>'100%'} %>
            
        </p>
        <p>
            <%= hash_table(@site.to_hash) %>
        </p>
       
        
    </div>
</div>
        