config/routes.rb
Bdb::Application.routes.draw do

  # resources :species, :only => [:show], :defaults => { :format => 'json' }
  get 'species/:id', to: 'species#show', defaults: { format: 'json' }
  get "species", to: 'species#search', defaults: {format: 'json'}

  
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users,  :skip => [:registrations]  #:controllers => { :invitations => "invitations" },
  
  resources :specimens, :only => [:index, :show, :edit]
  # printing a specimen has a side effect of updating printed date, so it's a put not a get
  
  
   
  resources :teams do 
    # dashboard page
    get 'collect' => 'dashboard#collect'
             
    
    resources :managers
    
    resources :collection_events do
      resource :specimens, :only => [:new, :create]
    end
    # , :except => [:new, :create]
    resources :specimens, :only => [:index, :show, :edit, :update, :destroy] do 
      collection do
        put "print", to: 'specimens#print_labels',  defaults: { format: 'pdf'}
      end
    end
    
    
    resources :sites do 
      resources :collection_events do
        resources :specimens
      end
    end
    
  end
  
  as :user do
    get 'users/registration' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    put 'users/registration' => 'devise/registrations#update', :as => 'user_registration' 
    delete 'users/registration' =>  'devise/registrations#delete', :as => 'delete_user_registration'          
  end 
  
  resources :users do 
    member do
       put 'invite'
     end
  end
   
  
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, # :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :team_id, :role_ids, :name, :email, :password, :password_confirmation, :remember_me, :firstname,  :lastname, :affiliation, :position, :contact,  :added_by_id, :notes, :as => :admin  
  attr_accessible :team_id, :role_ids, :name, :email, :password, :password_confirmation, :remember_me, :firstname,  :lastname, :affiliation, :position, :contact,  :added_by_id, :notes
  
  validates :firstname, :presence => true
  validates :lastname, :presence => true
  validates_associated :team                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  
  belongs_to :team
  
  default_scope :order => 'lastname, firstname'
  scope :managers, lambda { 
      joins(:roles).where("roles.name=?", 'manager')
    }
    
  before_validation(:on => :create) do
     self.password = Devise.friendly_token[0,20] if self.password.nil? 
     add_default_role
  end
  
  def name
    "#{firstname} #{lastname}"
  end
  
  def collector_name
    "#{firstname[0]}. #{lastname}"
  end
  
  def name=(bothnames)
    self.firstname, self.lastname = bothnames.split(" ")
  end
  
  def registered?
    self.invited_to_sign_up? || self.invitation_accepted?
  end
  
  def invitable?
    self.email? && !self.invitation_accepted? # removing this condition as confirmable option removed && !self.confirmed_at?
  end

  def add_default_role
    self.add_role :user if self.roles.empty?
  end
  
  def manager?
    self.roles_name.include?("manager")
  end
  
  # HACKS to deal with unintential upgrade to Devise 3 and Devise_invtable 1.3 which have different fields
  # and different methods.  
  
  # BETTER => USE A METHOD ALIAS
  def invitation_created_at
    self.invitation_sent_at
  end
  
  # this is added just to make the model compatible with Devise 3
  def invitation_created_at=(date)
    self.invitation_sent_at = date
  end

  #  override devise_invitable method to work with the truncated 60char keys        
  #  can't just truncate all tokens since I removed the limit on the token field for future invites

  def self.find_by_invitation_token(original_token, only_valid)
    invitation_token = Devise.token_generator.digest(self, :invitation_token, original_token)

    invitable = find_or_initialize_with_error_by(:invitation_token, invitation_token)
    
    # HACK to deal with LIMIT 60 shortened tokens
    if !invitable.persisted? 
      invitable = User.find_or_initialize_with_error_by(:invitation_token, invitation_token[0..59])
    end
    
    if !invitable.persisted? && Devise.allow_insecure_token_lookup
      invitable = find_or_initialize_with_error_by(:invitation_token, original_token)
    end
    invitable.errors.add(:invitation_token, :invalid) if invitable.invitation_token && invitable.persisted? && !invitable.valid_invitation?
    invitable.invitation_token = original_token
    invitable unless only_valid && invitable.errors.present?
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    authorize! :read, @user, :message => 'Not authorized as an administrator.'    
  end
  
  def edit
    @user = User.find(params[:id])
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
  end
  
  def update
    @user = User.find(params[:id])  
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    
    if @user.update_attributes(params[:user])
      redirect_to user_path(@user), :notice => "User updated."
    else
      redirect_to user_path(@user), :alert => "Unable to update user."
    end
  end
  
  def new
    @user = User.new()
    set_team!
    authorize! :update, @team, :message => "You are not authorized as a team manager"
    @user.team = @team
      
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end    
  end
  
  def create
    # make user act like nested resource for team.  All users must have a team
    @user = User.new(params[:user])
    set_team!
    @user.team = @team
    
    authorize! :update, @team, :message => "You are not authorized to manage team #{@team.name}"
    authorize! :create, @user, :message => "You are not authorized to create users"
    
    respond_to do |format|    
      if @user.save
        msg = "A record for #{@user.name} was created in team #{@team.name}. "
        if params[:send_invite_flag] && @user.invitable?
            if @user.invite!
              msg << " An invitation was sent to #{@user.email} "
            end
        end
        
        format.html { redirect_to @team, notice: msg }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
    
  def destroy
    @user = User.find(params[:id])
    set_team!
    
    unless @user == current_user
      authorize! :destroy, @user, :message => 'Not authorized as an manager.'
      @user.destroy
      redirect_to team_path(@team), :notice => "User deleted."
    else
      redirect_to root_url, :notice => "Can't delete your own user account."
    end
  end
  
  def invite
    @user = User.find(params[:id])
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    
    if !@user || !@user.invitable?
      redirect_to user_path(@user), :alert => "Unable to invite user."
      return
    end
    
    if @user.invite!(current_user)
      redirect_to user_path(@user), :notice => "Invitation sent to #{@user.email}."
    else
      redirect_to user_path(@user), :alert => "Unable to send invite to user."
    end
 end
  
  private

  # get a team record from something, somehow!
  def set_team!
    unless @team
      @team = Team.find(params[:team_id]) if params[:team_id]
    end
  
    unless @team
        if @user && @user.team_id?
          @team = @user.team
        end
    end
    
    unless @team
      @team = current_user.team
    end
    
    @team
  end
       
    
end

app/helpers/users_helper.rb
module UsersHelper

  def user_hash(user)
    {                                                              
      "Name" => user.name, 
      "Position" => user.position,                                   
      "email" => user.email    ,                                     
      "Affiliation" => user.affiliation,                             
      "Contact"=> user.contact         ,                             
      "Has database account?" => account_yes_no(user), 
      "Invitation?" => invitation_status(user),  
      "Roles" => user.roles_name.join(",") ,  
      "Team" => (user.team.name if user.team ), 
      "Notes" => (user.notes)
    }
    
  end
  
  def invitation_status(user)
    if user.invitation_accepted_at?
      "Accepted #{user.invitation_accepted_at.to_date.to_s}"
    elsif user.invitation_sent_at?
      "Sent #{user.invitation_sent_at.to_date.to_s}"
    else
      "Not Invited"
    end
  end
  
  def account_yes_no(user)
    (user.registered? ? "Yes" : "No")
  end
  

end

app/views/users/_role_modal.html.erb
<%# role modal, can be opened with button like a data-toggle="modal" href="#role-options- user.id %>

<div id="role-options-<%= user.id %>" class="modal" style="display: none;"> 
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<!-- Role modal -->

<%= simple_form_for user,  :html => { :class => 'form-horizontal' }  do |f| %> <%# :url => user_path(user) %>
    
    <%= f.error_notification %>

    <%= display_base_errors resource %>
    <div class="row">
        <div class="span4">
              <%= f.input :firstname, :autofocus => true, :hint => "Name is required",  :required => true %>
              <%= f.input :lastname, :autofocus => true, :hint => "Name is required",  :required => true %>
              <%= f.input :email, :required => true %>
           </div>
          <div class="span4">
              <%= f.input :position,  :hint => "Job title or description" %>
              <%= f.input :affiliation,    :hint => "Company, project,institution, ..." %>
              <%= f.input :contact,  :hint => "Full address, phone, etc.",  :input_html => { :cols => 30, :rows => 7 } %>
           </div> 
    </div>
    <hr>
    
    <% if user.new_record? %>
        <%= f.hidden_field :added_by_id, :value => current_user.id                   %>
        <%= f.hidden_field :team_id,     :value => ( user.team_id || @team.team_id ) %>
    <% end -%>
    
    <% if user.new_record? || user.invitable? %> <%# && can? :manage, user %>
        <%= check_box_tag 'send_invite_flag' -%>     
        <%= label_tag  "Create user account and send invitation?" %>
    <% end -%>
    
    <%= f.input :notes, :hint => "Comments, notes about this person",  :input_html => { :cols => 80, :rows => 4, :style=>"width:auto" } %>
    
    
    <%= f.submit :class=>"btn primary" %>
    
<% end %>

app/views/users/_user_buttons.html.erb
<% style ||= "unstyled" %>
<ul class="<%= style %>">
    <li class="active">
        <%= link_to "Show Profile", user_path(user) %>
    </li>
    <li>
        <%= iconified_link_to 'icon-pencil', "Edit Profile", edit_user_path(user) %>
    </li>
    
    <% if can? :manage, User    %>
        <% if user.invitable? %>
        <li> 
            <%= iconified_link_to 'icon-envelope', "Send Invite", invite_user_path(user), :method => :put %>  <!-- }, html_options =  -->
        </li>
        <% end %>
        <li>
            <a data-toggle="modal" href="#role-options-<%= user.id %>" ><i class="icon-briefcase"></i> Change role</a>
        </li>
        <li>
            <%= iconified_link_to('icon-trash', 'Delete user', user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete) unless user == @current_user %>
        </li>
    <% end %>
</ul>

<% if can? :manage, User %>
    <%= render "users/role_modal", {:user => user} %>
<%- end %>

app/views/users/_users.html.erb
<%# local variable for setting the table HTML ID attribute, to allow for >1 tables per page %>
<% table_id ||= 'users_table' %>

<% content_for :head do %>
    <script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        var utable =  $('#<%= table_id %>')
          utable.dataTable({
              "sDom": '<"row"<"span3"i><"span4"f><"span5">r>t<"row"<"span3"l><"pull-right">p>>>',
              "iDisplayLength": 25,
              "sPaginationType": "bootstrap"  
        });
    });

    </script>
<% end -%>


<table class="table table-bordered users_table" id="<%= table_id %>">
  <thead>
    <tr>
      <th>Name</th>
      <th>email</th>
      <th>Team</th>
      <th>Position, Affiliation</th>
      <th>Created on</th>
      <th>Invitation sent/accepted</th> 
    <th>Registered?</th>
      <th>Sign in count/date</th>
      <th>Role</th>
    </tr>
  </thead>
  <tbody>
  <% users.each do |user| %>
    <tr>
     <td>
         <% if can? :read, user %>
              <%= iconified_button_to "icon-user", user.name, user %>
           <% else -%>
              <%= user.name %>
           <% end -%>
     </td>
     <td>
           <%= user.email %>
     </td>
     <td>
         <% unless user.team.blank? %>
         <% if can? :manage, Team %>
             <%= link_to user.team.name, team_path(user.team.id) %>
         <% else %>
             <%= user.team.name %>
         <% end %>
         <% end %>
    </td>   
    <td>
        <%= user.position %> <br/>  
        <%= user.affiliation %>
    </td>  
     <td>
         <%= user.created_at.to_date %>
     </td>
      <td>
          <%= user.invitation_sent_at.to_date  if user.invitation_sent_at %> <br><%= user.invitation_accepted_at.to_date if user.invitation_accepted_at %>
      </td>     
     <td>
          <%= account_yes_no(user) %>
     </td>
      <td>
          <%= user.last_sign_in_at %><br/>
          <%= user.sign_in_count %>#

      </td>
      <td>
          <%= user.roles.first.name.titleize unless user.roles.first.nil? %>
      </td>

    </tr>
  <% end -%>
  </tbody>
</table>

app/views/users/edit.html.erb
<% title("Edit Profile: #{@user.name}") %>

<%= render :partial=>'user', :locals => {:user => @user} %>

<% content_for :subnav do -%>
<ul class="nav pull-right">
    <li><%= iconified_link_to 'icon-remove', "Cancel Edits, return to profile", @user %></li>
</ul>
<% end -%>

app/views/users/index.html.erb
<% title("All Project Users") %>
<div class="span8">
    <%= render "users", {:users => @users,:style=>"inline"} %>
</div>

app/views/users/new.html.erb
<% title('New User') %>
<div class="row">
    
    <div class="span6">
        <%= render 'user', {:user => @user} %>
    </div>
    
    <div class="span4 offset2">
        <p>Users created here do not have accounts to log-in unless you invite them to do so.</p>   
    </div>


</div>

app/views/users/show.html.erb
<% title("User Profile: #{@user.name}") %>

<% content_for :subnav do -%>
    <%= render "user_buttons", {:user => @user, :style=>'nav' } %>             
<% end -%>

<div class="row">
    <div class="span6">
        
        <div class="well">
            <%= hash_table(user_hash(@user)) %>
        </div>
    </div>
    
    <div class="span6">

    </div>
</div>