config/routes.rb
Bdb::Application.routes.draw do

  # resources :species, :only => [:show], :defaults => { :format => 'json' }
  get 'species/:id', to: 'species#show', defaults: { format: 'json' }
  get "species", to: 'species#search', defaults: {format: 'json'}

  
  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users,  :skip => [:registrations]  #:controllers => { :invitations => "invitations" },
  
  resources :specimens, :only => [:index, :show, :edit]
  # printing a specimen has a side effect of updating printed date, so it's a put not a get
  
  
   
  resources :teams do 
    # dashboard page
    get 'collect' => 'dashboard#collect'
             
    
    resources :managers
    
    resources :collection_events do
      resource :specimens, :only => [:new, :create]
    end
    # , :except => [:new, :create]
    resources :specimens, :only => [:index, :show, :edit, :update, :destroy] do 
      collection do
        put "print", to: 'specimens#print_labels',  defaults: { format: 'pdf'}
      end
    end
    
    
    resources :sites do 
      resources :collection_events do
        resources :specimens
      end
    end
    
  end
  
  as :user do
    get 'users/registration' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    put 'users/registration' => 'devise/registrations#update', :as => 'user_registration' 
    delete 'users/registration' =>  'devise/registrations#delete', :as => 'delete_user_registration'          
  end 
  
  resources :users do 
    member do
       put 'invite'
     end
  end
   
  
end

app/views/layouts/_errors.html.erb
 <% if object.errors.any? %>
 
<div id="error_explanation" >
   <div class="alert alert-error">
     The form contains <%= pluralize(object.errors.count, "error") %>:
  
   <ul class="unstyled">
     <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
     <% end %>
   </ul>
    </div>
</div>
<% end -%>

app/views/layouts/_footer.html.erb
<ul class="inline muted">
  <li>ICP Bee Database: BDB</li>
  <li>Copyright (c) 2013 ICP Team</li>
  <li><a href="http://icpbees.org">Integrated Crop Pollination Project</a></li>
  <li><a href="http://www.isaacslab.ent.msu.edu">R Isaacs Lab</a></li>
  <li><%= link_to "home", "http://" + ENV["APP_HOST"] %></li>
</ul>

app/views/layouts/_gmap.html.erb
<% 
    # set some default values
    site ||= sites[0] 
    height ||= 500
    width  ||= 500
    zoom_set   ||= 12
    map_element_id  ||='map-canvas'
%>
<%= content_for :head do %>

    <style>
      #<%= map_element_id %> img { max-width:none; }
      #<%= map_element_id %> {
        margin: 0;
        padding: 0;
        height: 100%;
      }
      
      .gmnoprint img { max-width: none; }
    </style>
    
    <script src="http://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLEKEY'] -%>&sensor=false" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript" charset="utf-8">
        
    function initialize() {
        
        // var latlngbounds = new google.maps.LatLngBounds();
        
        var mapOptions = {
            mapTypeId: google.maps.MapTypeId.TERRAIN,
            mapTypeControl: true,
            mapTypeControlOptions: {
              style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
            },
            zoomControl: true,
            zoomControlOptions: {
              style: google.maps.ZoomControlStyle.DEFAULT
            }
           
        };

        // var originalCoords = '<%= site.coordinates if site %>';
        
        var map = new google.maps.Map(document.getElementById('<%= map_element_id %>'),
          mapOptions);

          <% if sites.blank? || site.blank? || sites[0].coordinates.blank? & %>
              mapWithoutMarkers(map);
              <% else %>
              mapWithMarkers(map);
          <% end %>
                  
    }

    function mapWithMarkers(map3){
        var latlngbounds = new google.maps.LatLngBounds();
        var minZoom = 15;
        
        <% for site in sites %>
            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(<%= site.coordinates if site %>),
                map: map3, 
                url: '<%= team_site_path(@team, site.id) if site.id? %>', 
                title: '<%= site.name if site.name? %>'
            });

            latlngbounds.extend(new google.maps.LatLng(<%= site.coordinates if site %>))
            google.maps.event.addListener(marker, 'click', function() {
                window.location.href = this.url;
             });
        
             <% if sites.count == 1 %>
                 addMarkerListener(map3, marker)  
             <% end %>
            
        <% end -%>
        
        google.maps.event.addListener(map3, 'zoom_changed', function() {
            zoomChangeBoundsListener = 
                google.maps.event.addListener(map3, 'bounds_changed', function(event) {
                    if (this.getZoom() > minZoom && this.initialZoom == true) {
                        // Change max/min zoom here
                        this.setZoom(minZoom);
                        this.initialZoom = false;
                    }
                google.maps.event.removeListener(zoomChangeBoundsListener);
            });
        });
        
        map3.initialZoom = true;
        map3.setCenter(latlngbounds.getCenter());
        map3.fitBounds(latlngbounds); 
    }
    
    function mapWithoutMarkers(map4){        
        map4.setCenter(new google.maps.LatLng(<%= default_coordinates %>));
        map4.setZoom(3);        
        addMarkerListener(map4)  
    }

    
    function addMarkerListener(map,marker){
        google.maps.event.addListener(map, 'click', function(event) {
            var latfield = document.getElementById('site_latitude');
            var lngfield = document.getElementById('site_longitude');
        
            latfield.value = event.latLng.lat();
            lngfield.value = event.latLng.lng();
       
            if (marker) { marker.setMap(null); }

            marker = new google.maps.Marker({ position: event.latLng, map: map }
            );
        
        });
    }
    
    

    
    
    google.maps.event.addDomListener(window, 'load', initialize);
    
    

    </script>

<% end -%>
    

<div id="<%= map_element_id %>" style="height:<%= height %>px; width:<%= width %>px;background-color:gray"></div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
    <li class="">
        <%= link_to "<strong>Bee DB</strong>".html_safe, root_url, :class=>"text-success" %>
    </li>
    <% if user_signed_in?  %>
    
    <% if @team and not(@team.new_record?) %>
    <li class="dropdown">
        <a href="<%= team_collect_path(@team) %>" class="dropdown-toggle" data-toggle="dropdown">
          Collect<b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
             <li>
                 <%= link_to "Dashboard", team_collect_path(@team) %>
            </li>
            <li>
                <%= link_to 'Collections Sites', team_sites_path(@team) %>
            </li>

            <li>
                <%= link_to "All Collection Events", team_collection_events_path(@team) %>
            </li>
            <li>
                <%= link_to "All Specimens", team_specimens_path(@team)%>
            </li>
            <li>
                <%= iconified_link_to 'icon-qrcode', "Print new labels", print_team_specimens_path(@team), :method=>:put, :confirm => "Make PDF and update print date all unprinted labels?" %>
            </li>
            <li>
                <%= link_to 'New Site', new_team_site_path(@team)  %>
            </li>
        </ul>
    </li>
    
    
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Reporting<b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
           <li>
               <%= iconified_link_to 'icon-list-alt', "All Specimens Collected by #{@team}", team_specimens_path(@team) %>
           </li>
           <li>
               <%= iconified_link_to 'icon-qrcode', "All labels for reference", team_specimens_path(@team,:format=>:pdf) %>
           </li>
           
            <li>
                <%= iconified_link_to 'icon-file', 'Specimen CSV Export', team_specimens_path(@team,:format=>:csv) %>
            </li>
        </ul>
    </li>
    <% end -%>
            
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Team<b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
              <li>
                  <%= link_to 'Your Team', team_path(current_user.team.id) %>
              </li>
              <li>
                  <%= link_to 'Other Teams', teams_path %>
              </li>
        </ul>
     </li>      

    <% end %>
     
</ul>

    
<ul class="nav pull-right" role="menu" aria-labelledby="dLabel">
    <% if user_signed_in? && current_user.has_role?( :admin) %>

    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             <i class="icon-wrench"></i>
          Admin<b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'New User', new_user_path %></li>
            <li><%= link_to 'Teams', teams_path %></li>
            <li><%= link_to 'New Team', new_team_path %></li>
        </ul>
      </li>
    
    <% end %>
        
  <% if user_signed_in? %>
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="icon-user"></i>
            <%= current_user.name %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
              <li>
                  <%= link_to 'Profile', user_path(current_user) %>
              </li>
              <li>
                  <%= link_to 'Change Password', edit_user_registration_path %>
              </li>
              <li>
                  <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
              </li>
        
          </ul>
        </li>
        
      <% else %>
        
      <li>
       <%= link_to 'Login', new_user_session_path%>
      </li>
    <% end %>
    
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>ICP Bee Database | <%= yield(:title) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bdb" %>">
    <%= favicon_link_tag "favicon.ico" %>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %> 

    <%= csrf_meta_tags %>

    <%= yield(:head) %>
        
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container-fluid">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container-fluid">
        <div class="content">
           <div class="row span12">
            <!-- <div class="span12"> -->

                <% if content_for?(:title) %>
                <div class="navbar">
                  <div class="navbar-inner">
                      <a class="brand" href="#"><%= yield(:title) %></a>                      
                      <%= yield(:subnav) %>
                  </div>
                </div>
                <% end %>

              <%= render 'layouts/messages' %>

              <%= yield %>              

            <!-- </div> -->
          </div>
        </div>
      </div> <!--! end of .container -->
     
      <div id="footer">
              
            <div class="span6">
                    <%= link_to  root_path do %>
                        <%= image_tag "icp_bee_icon.png", :size=>"30x30" %>
                    <% end -%>
                    <%= yield(:footer) %>
            </div>
            <div class="span6 pull-right">
                <%= render "layouts/footer" %>
            </div>
    
            
      </div>
    </div> <!--! end of #main -->
    <%= yield :scripts %>
 
  </body>
</html>